dist: xenial
language: python
jobs:
  include:
  - python: "3.2"
    dist: trusty
  - python: "3.3"
    dist: trusty
  - python: "3.4"
  - python: "3.5"
  - python: "3.6"
  - python: "3.7"
  - python: "3.8"
  - python: "3.9-dev"
before_install:
- pyflakes=pyflakes
- if [[ $TRAVIS_PYTHON_VERSION = 3.[23] ]]; then pyflakes='pyflakes<2'; fi
- if [[ $TRAVIS_PYTHON_VERSION = 3.2 ]]; then if_pygments=:; fi
install:
- python3 -m pip install pydiatra $pyflakes
- $if_pygments python3 -m pip install restructuredtext-lint pygments
script:
- prove -v
- python3 -m pydiatra .
- python3 -m pyflakes .
- $if_pygments restructuredtext-lint --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
